In [86]:
import jax.numpy as jnp
def compute_accuracy(logits, labels):
    return jnp.mean(jnp.argmax(logits, -1) == labels).block_until_ready()

In [72]:
ones_1D = jnp.zeros((1, 3, 3, 1))
ones_1D = ones_1D.at[:,:,2,:].set(1)
print(ones_1D)

[[[[0.]
   [0.]
   [1.]]

  [[0.]
   [0.]
   [1.]]

  [[0.]
   [0.]
   [1.]]]]


In [85]:
print(jnp.argmax(ones_1D),0)

2 0


In [56]:
array_size = (1,512,512,1)
logits_dummy = jnp.zeros(array_size)
logits_dummy = logits_dummy.at[0,10:20,50:100,0].set(1)
labels_dummy = jnp.zeros(array_size)
print(logits_dummy)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]]


In [68]:
jnp.argmax(logits_dummy, 2) == 0

DeviceArray([[[ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [False],
              [False],
              [False],
              [False],
              [False],
              [False],
              [False],
              [False],
              [False],
              [False],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
              [ True],
           

In [61]:
print((jnp.argmax(logits_dummy, 0) == labels_dummy).block_until_ready())

[[[[ True]
   [ True]
   [ True]
   ...
   [ True]
   [ True]
   [ True]]

  [[ True]
   [ True]
   [ True]
   ...
   [ True]
   [ True]
   [ True]]

  [[ True]
   [ True]
   [ True]
   ...
   [ True]
   [ True]
   [ True]]

  ...

  [[ True]
   [ True]
   [ True]
   ...
   [ True]
   [ True]
   [ True]]

  [[ True]
   [ True]
   [ True]
   ...
   [ True]
   [ True]
   [ True]]

  [[ True]
   [ True]
   [ True]
   ...
   [ True]
   [ True]
   [ True]]]]


### new accuracy

In [4]:
import jax.numpy as jnp
from flax.linen import sigmoid
# sigmoid_to_binary = lambda x : 1 if x >= 0.5 else 0
def logits_to_binary(logits):
    logits = sigmoid(logits)
    logits = logits.round()
    return logits

In [16]:
from jax import random
x_key = random.PRNGKey(0)
y_key = random.PRNGKey(1)
x = random.normal(x_key, (1,512,512,1))
y = random.normal(y_key, (1,512,512,1))
print(x.shape)

(1, 512, 512, 1)


In [17]:
x = logits_to_binary(x)
y = logits_to_binary(y)

In [18]:
def compute_accuracy(logits, labels):
    return jnp.mean(logits == labels)

In [19]:
compute_accuracy(x, y)

DeviceArray(0.4994278, dtype=float32)